# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "catalina.box"

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]

    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    vb.memory = "8192"
    vb.cpus = 4
    
	vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
	vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
	vb.customize ["setextradata", :id, "VBoxInternal2/EfiGopMode", "4"]
  end

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder ".", "/vagrant", disabled: true
#   config.vm.synced_folder '/System/Volumes/Data/Users/tommaso/Documents', '/Users/vagrant/shared', type: 'virtualbox'
#   nfsPath = ".."
#   if Dir.exist?("/System/Volumes/Data")
# 	  nfsPath = "/System/Volumes/Data" + Dir.pwd
#   end
#   config.vm.synced_folder nfsPath, "/shared", 
#   		type: "nfs", 
#   		create: true, 
#         id: "core",
#         :nfs => true,
#         :mount_options => ['nolock,vers=3,udp,noatime,actimeo=1,resvport'],
#     :export_options => ['async,insecure,no_subtree_check,no_acl,no_root_squash']


  config.vm.provision :shell, path: "bootstrap.sh", privileged: false
  config.vm.provision :shell, path: "build.sh", privileged: false, run: "always"
end
