version: '2'
services:
#   debian:
#     privileged: true
#     build:
#        context: ./debian
#     command: /build.sh
#     entrypoint: /build.sh
#     volumes:
#       - .:/mnt 
   cross32:
     privileged: true
     build:
        context: ./cross32
     command: /build.sh
     entrypoint: /build.sh
     volumes:
       - .:/mnt 
   cross64:
     privileged: true
     build:
        context: ./cross64
     command: /build.sh
     entrypoint: /build.sh
     volumes:
       - .:/mnt 
#   appimage:
#     privileged: true
#     build:
#        context: ./appimage
#     command: /build.sh
#     entrypoint: /build.sh
#     volumes:
#       - .:/mnt 
