version: '2'
services:
#   cross32:
#     privileged: true
#     build:
#        context: ./cross32
#     command: /build.sh
#     entrypoint: /build.sh
#     volumes:
#       - .:/mnt 
#   cross64:
#     privileged: true
#     build:
#        context: ./cross64
#     command: /build.sh
#     entrypoint: /build.sh
#     volumes:
#       - .:/mnt 
   ubuntu:
     privileged: true
     build:
        context: ./ubuntu
     command: /build.sh
     entrypoint: /build.sh
     volumes:
       - .:/mnt 
